# Generated by Django 5.2.17 on 2026-08-28 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted (anyone with the link)'), ('public', 'Public')], default='private', max_length=16)),
                ('share_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('harvest_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('roast_level', models.CharField(blank=True, choices=[('light', 'Light'), ('medium_light', 'Medium-light'), ('medium', 'Medium'), ('medium_dark', 'Medium-dark'), ('dark', 'Dark')], default='', max_length=16)),
                ('altitude_min_masl', models.PositiveIntegerField(blank=True, null=True)),
                ('altitude_max_masl', models.PositiveIntegerField(blank=True, null=True)),
                ('is_decaf', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='catalog.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='catalog.processmethod')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='catalog.producer')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='catalog.region')),
                ('roaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='catalog.roaster')),
                ('varietals', models.ManyToManyField(blank=True, related_name='coffees', to='catalog.varietal')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted (anyone with the link)'), ('public', 'Public')], default='private', max_length=16)),
                ('share_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('roast_date', models.DateField(blank=True, null=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('weight_grams', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_currency', models.CharField(blank=True, default='', max_length=3)),
                ('is_finished', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('purchased_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bags_sold', to='catalog.roaster')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='coffee.coffee')),
            ],
            options={
                'ordering': ['-purchase_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='coffee',
            index=models.Index(fields=['owner', '-created_at'], name='coffee_own_created'),
        ),
        migrations.AddIndex(
            model_name='coffee',
            index=models.Index(fields=['owner', 'name'], name='coffee_own_name'),
        ),
        migrations.AddConstraint(
            model_name='coffee',
            constraint=models.CheckConstraint(condition=models.Q(('harvest_year__isnull', True), models.Q(('harvest_year__gte', 1900), ('harvest_year__lte', 2100)), _connector='OR'), name='coffee_harvest_year_sane'),
        ),
        migrations.AddConstraint(
            model_name='coffee',
            constraint=models.CheckConstraint(condition=models.Q(('altitude_min_masl__isnull', True), ('altitude_max_masl__isnull', True), ('altitude_max_masl__gte', models.F('altitude_min_masl')), _connector='OR'), name='coffee_altitude_range'),
        ),
        migrations.AddIndex(
            model_name='bag',
            index=models.Index(fields=['owner', '-created_at'], name='bag_own_created'),
        ),
        migrations.AddIndex(
            model_name='bag',
            index=models.Index(fields=['owner', 'is_finished'], name='bag_own_finished'),
        ),
        migrations.AddIndex(
            model_name='bag',
            index=models.Index(fields=['coffee', '-created_at'], name='bag_coffee_created'),
        ),
        migrations.AddConstraint(
            model_name='bag',
            constraint=models.CheckConstraint(condition=models.Q(('weight_grams__isnull', True), ('weight_grams__gt', 0), _connector='OR'), name='bag_weight_positive'),
        ),
        migrations.AddConstraint(
            model_name='bag',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__isnull', True), ('price_amount__gte', 0), _connector='OR'), name='bag_price_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='bag',
            constraint=models.CheckConstraint(condition=models.Q(('roast_date__isnull', True), ('purchase_date__isnull', True), ('roast_date__lte', models.F('purchase_date')), _connector='OR'), name='bag_roasted_before_purchase'),
        ),
    ]
