# Generated by Django 5.2.17 on 2026-08-27 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedThing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted (anyone with the link)'), ('public', 'Public')], default='private', max_length=16)),
                ('share_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['owner', '-created_at'], name='ownedthing_own_created')],
            },
        ),
        migrations.CreateModel(
            name='ReferenceThing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='testapp.referencething')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='referencething_canon_slug'), models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='referencething_owned_slug')],
            },
        ),
    ]
