# Generated by Django 5.2.17 on 2026-08-28 04:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('iso_alpha2', models.CharField(max_length=2, unique=True)),
                ('iso_alpha3', models.CharField(max_length=3, unique=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.country')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grinder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted (anyone with the link)'), ('public', 'Public')], default='private', max_length=16)),
                ('share_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('burr_type', models.CharField(choices=[('conical', 'Conical burr'), ('flat', 'Flat burr'), ('blade', 'Blade'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('setting_min', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('setting_max', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('step_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('washed', 'Washed'), ('natural', 'Natural'), ('honey', 'Honey'), ('other', 'Other')], default='other', max_length=16)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.processmethod')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('altitude_min_masl', models.PositiveIntegerField(blank=True, null=True)),
                ('altitude_max_masl', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='catalog.country')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.region')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('altitude_min_masl', models.PositiveIntegerField(blank=True, null=True)),
                ('altitude_max_masl', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='catalog.country')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.producer')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='catalog.region')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roaster',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('website', models.URLField(blank=True, default='')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roasters', to='catalog.country')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.roaster')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.tastingnote')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.tastingnote')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Varietal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.varietal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.varietal')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('source', models.CharField(default='manual', max_length=64)),
                ('external_id', models.CharField(blank=True, default='', max_length=200)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('parameter_schema', models.JSONField(blank=True, default=dict)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='catalog.brewmethod')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='brewmethod_canon_slug'), models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='brewmethod_owned_slug')],
            },
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='country_canon_slug'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='country_owned_slug'),
        ),
        migrations.AddIndex(
            model_name='grinder',
            index=models.Index(fields=['owner', '-created_at'], name='grinder_own_created'),
        ),
        migrations.AddConstraint(
            model_name='grinder',
            constraint=models.CheckConstraint(condition=models.Q(('setting_max__gte', models.F('setting_min')), ('setting_min__isnull', True), ('setting_max__isnull', True), _connector='OR'), name='grinder_setting_range'),
        ),
        migrations.AddConstraint(
            model_name='processmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='processmethod_canon_slug'),
        ),
        migrations.AddConstraint(
            model_name='processmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='processmethod_owned_slug'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='region_canon_slug'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='region_owned_slug'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.CheckConstraint(condition=models.Q(('altitude_max_masl__gte', models.F('altitude_min_masl')), ('altitude_min_masl__isnull', True), ('altitude_max_masl__isnull', True), _connector='OR'), name='region_altitude_range'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='producer_canon_slug'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='producer_owned_slug'),
        ),
        migrations.AddConstraint(
            model_name='roaster',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='roaster_canon_slug'),
        ),
        migrations.AddConstraint(
            model_name='roaster',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='roaster_owned_slug'),
        ),
        migrations.AddConstraint(
            model_name='tastingnote',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='tastingnote_canon_slug'),
        ),
        migrations.AddConstraint(
            model_name='tastingnote',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='tastingnote_owned_slug'),
        ),
        migrations.AddConstraint(
            model_name='varietal',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', True)), fields=('slug',), name='varietal_canon_slug'),
        ),
        migrations.AddConstraint(
            model_name='varietal',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner', 'slug'), name='varietal_owned_slug'),
        ),
    ]
