# Generated by Django 5.2.17 on 2026-08-28 08:41

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted (anyone with the link)'), ('public', 'Public')], default='private', max_length=16)),
                ('share_token', models.UUIDField(blank=True, db_index=True, editable=False, null=True, unique=True)),
                ('brewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dose_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('water_grams', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('water_temp_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('grind_setting', models.CharField(blank=True, default='', max_length=64)),
                ('grind_microns', models.PositiveIntegerField(blank=True, null=True)),
                ('total_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('bloom_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('bloom_water_grams', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('pressure_bar', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('yield_grams', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('liked', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('acidity', models.PositiveSmallIntegerField(blank=True, help_text='1 (flat) to 5 (bright)', null=True)),
                ('sweetness', models.PositiveSmallIntegerField(blank=True, help_text='1 (dry) to 5 (sweet)', null=True)),
                ('body', models.PositiveSmallIntegerField(blank=True, help_text='1 (thin) to 5 (heavy)', null=True)),
                ('bitterness', models.PositiveSmallIntegerField(blank=True, help_text='1 (none) to 5 (harsh)', null=True)),
                ('aftertaste', models.PositiveSmallIntegerField(blank=True, help_text='1 (short) to 5 (lingering)', null=True)),
                ('extras', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-brewed_at'],
                'abstract': False,
            },
        ),
    ]
