# Generated by Django 5.2.17 on 2026-08-28 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brewing', '0001_initial'),
        ('catalog', '0001_initial'),
        ('coffee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='bag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brews', to='coffee.bag'),
        ),
        migrations.AddField(
            model_name='brew',
            name='grinder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brews', to='catalog.grinder'),
        ),
        migrations.AddField(
            model_name='brew',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brews', to='catalog.brewmethod'),
        ),
        migrations.AddField(
            model_name='brew',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_notes',
            field=models.ManyToManyField(blank=True, related_name='brews', to='catalog.tastingnote'),
        ),
        migrations.AddIndex(
            model_name='brew',
            index=models.Index(fields=['owner', '-created_at'], name='brew_own_created'),
        ),
        migrations.AddIndex(
            model_name='brew',
            index=models.Index(fields=['bag', '-brewed_at'], name='brew_bag_brewed'),
        ),
        migrations.AddIndex(
            model_name='brew',
            index=models.Index(fields=['owner', '-brewed_at'], name='brew_own_brewed'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('dose_grams__isnull', True), ('dose_grams__gt', 0), _connector='OR'), name='brew_dose_positive'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('water_grams__isnull', True), ('water_grams__gt', 0), _connector='OR'), name='brew_water_positive'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('water_temp_c__isnull', True), models.Q(('water_temp_c__gte', 0), ('water_temp_c__lte', 100)), _connector='OR'), name='brew_water_temp_range'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('yield_grams__isnull', True), ('yield_grams__gt', 0), _connector='OR'), name='brew_yield_positive'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('acidity__isnull', True), models.Q(('acidity__gte', 1), ('acidity__lte', 5)), _connector='OR'), name='brew_acidity_range'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('sweetness__isnull', True), models.Q(('sweetness__gte', 1), ('sweetness__lte', 5)), _connector='OR'), name='brew_sweetness_range'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('body__isnull', True), models.Q(('body__gte', 1), ('body__lte', 5)), _connector='OR'), name='brew_body_range'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('bitterness__isnull', True), models.Q(('bitterness__gte', 1), ('bitterness__lte', 5)), _connector='OR'), name='brew_bitterness_range'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('aftertaste__isnull', True), models.Q(('aftertaste__gte', 1), ('aftertaste__lte', 5)), _connector='OR'), name='brew_aftertaste_range'),
        ),
    ]
